cache:
  paths:
    - build/

stages:
  - clean
  - configure
  - build
  - test
  - package

.linux:
  tags:
    - linux

.windows:
  tags:
    - windows

# Clean
.clean:
  stage: clean
  script:
    - cmake -E remove_directory build
  when: manual

clean-linux:
  extends:
    - .clean
    - .linux

clean-windows:
  extends:
    - .clean
    - .windows

# Configure
.configure:
  stage: configure
  script:
    - cmake -E make_directory build
    - cd build
    - cmake $ARCH_PARAM -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..

configure-linux:
  extends:
    - .configure
    - .linux

configure-windows:
  extends:
    - .configure
    - .windows
  variables:
    ARCH_PARAM: -Ax64

# Build
.build:
  stage: build
  script:
    - cmake --build build --config Release

build-linux:
  extends:
    - .build
    - .linux
  needs:
    - configure-linux

build-windows:
  extends:
    - .build
    - .windows
  needs:
    - configure-windows

# Test
.test:
  stage: test
  script:
    - cd build
    - ctest -C Release -j 8

test-linux:
  extends:
    - .test
    - .linux
  needs:
    - configure-linux
    - build-linux

test-windows:
  extends:
    - .test
    - .windows
  needs:
    - configure-windows
    - build-windows

# Package
.package:
  stage: package
  script:
    - cd build
    - cpack -C Release
  only:
    - master

package-linux:
  extends:
    - .package
    - .linux
  needs:
    - configure-linux
    - build-linux
    - test-linux
  artifacts:
    paths:
      - build/f3d-*.tar.gz
      - build/f3d-*.tar.xz

package-windows:
  extends:
    - .package
    - .windows
  needs:
    - configure-windows
    - build-windows
    - test-windows
  artifacts:
    paths:
      - build/f3d-*.zip
      - build/f3d-*.exe
